### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pulkitsinghal** [clarkbw/loopback-mixins-example#1]
This is my way of committing my hours and a PR somewhere in the near future after I take this for a spin. Because right now the README doesn't talk the user through anything and I'll provide what I did to learn from and make the most of your example.

**Comment by clarkbw** [comment]
That would be awesome!  Looking forward to it.

**Comment by pulkitsinghal** [comment]
https://github.com/clarkbw/loopback-mixins-example/pull/2

**Comment by clarkbw** [comment]
> Would be overkill to do a 2 minute video?

If you want to make a video I'll link to it in the README if its useful.

Thanks again for fixing up the README.
