### ISSUE TITLE
Contribute repo to StrongLoop examples?

### ISSUE THREAD

**Issue by crandmck** [clarkbw/loopback-mixins-example#3]
Hi @clarkbw, @raymondfeng suggested that I ask if you'd be willing to contribute this repo to the set of LoopBack example apps?  

If you're amenable, I would create a https://github.com/strongloop/loopback-example-mixins repo and we'd copy this repo it (or perhaps [transfer it](https://help.github.com/articles/transferring-a-repository/), your call).  This is an area that we're working on documenting better and providing good examples is a key part of that. Thanks for creating it!

**Comment by clarkbw** [comment]
Hi @crandmck that sounds good to me.  I can transfer it in, it looks like you'll need to create a temp admin group for me to accomplish that.  Just let me know in this issue if you want to continue that way and when the group is setup so I can do the transfer.

**Comment by raymondfeng** [comment]
@clarkbw What about that we create an empty `loopback-example-mixins` and you can just contribute it back via a PR?

**Comment by clarkbw** [comment]
@raymondfeng sure, I can do that too.

**Comment by crandmck** [comment]
I created https://github.com/strongloop/loopback-example-mixins
@clarkbw please add your example to this repo.  Thank You!
/cc @superkhau FYI

**Comment by superkhau** [comment]
Can you rename it to loopback-example-mixins to follow the convention?

**Comment by crandmck** [comment]
@superkhau that IS the name....(?)

**Comment by superkhau** [comment]
@crandmck I was looking on my phone and realized I was looking at @clarkbw's repo name. I erased the message hoping to undo it, but it looks like GitHub still sent you the message. ;)

**Comment by crandmck** [comment]
@superkhau No worries!

**Comment by clarkbw** [comment]
Created strongloop/loopback-example-mixins#1 to make the transfer, closing this issue out.  We can continue with issues in the new repo.  I'll start shutting this repo down to point to the new strongloop one.

**Comment by crandmck** [comment]
Thanks for the contribution @clarkbw !
